/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.home.security.view;
import sun.audio.*;
import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import smart.home.security.model.Devices;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author chana
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        armButton = new javax.swing.JButton();
        disarmButton = new javax.swing.JButton();
        enableButton = new javax.swing.JButton();
        disableButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SMART HOME SECURITY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(408, 309));

        addButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        addButton.setText("Add Device");
        addButton.setToolTipText("Add a device");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        removeButton.setText("Remove Device");
        removeButton.setToolTipText("Remove a device");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        armButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        armButton.setText("Arm System");
        armButton.setToolTipText("Arm system");
        armButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armButtonActionPerformed(evt);
            }
        });

        disarmButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        disarmButton.setText("Disarm System");
        disarmButton.setToolTipText("Disarm system");
        disarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disarmButtonActionPerformed(evt);
            }
        });

        enableButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        enableButton.setText("Enable Device");
        enableButton.setToolTipText("Enable device");
        enableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableButtonActionPerformed(evt);
            }
        });

        disableButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        disableButton.setText("Disable Device");
        disableButton.setToolTipText("Disable a device");
        disableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        statusLabel.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(armButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(enableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(disarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(disableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(armButton)
                    .addComponent(enableButton))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton)
                    .addComponent(disarmButton)
                    .addComponent(disableButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private SmartHomeSecurityFrame getSmartHomeSecurityFrame() {
        return (SmartHomeSecurityFrame) SwingUtilities.getWindowAncestor(this);
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddDevicePanel addDevicePanel = new AddDevicePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(addDevicePanel);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        RemoveDevicePanel removeDevicePanel = new RemoveDevicePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(removeDevicePanel);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void armButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armButtonActionPerformed
        Devices.getInstance().armDevices();
        statusLabel.setText("System Armed");// To change the staus of the label
        armButton.setEnabled(false);// To disable the enable button after the first click
        disarmButton.setEnabled(true);// To keep the disable button focused until the button is clicked
         InputStream inputStream;
        try {
          inputStream = new FileInputStream(new File("/Users/chana/Music/iTunes/iTunes Media/Music/Unknown Artist/Unknown Album/arm.wav"));
            AudioStream audios = new AudioStream(inputStream);
            AudioPlayer.player.start(audios);
        }
       catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_armButtonActionPerformed

    private void disarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disarmButtonActionPerformed
        Devices.getInstance().disarmDevices();
        statusLabel.setText("System Disarmed");
        armButton.setEnabled(true);
        disarmButton.setEnabled(false);
        InputStream inputStream;
        try {
          inputStream = new FileInputStream(new File("/Users/chana/Music/iTunes/iTunes Media/Music/Unknown Artist/Unknown Album/disarm.wav"));
            AudioStream audios1 = new AudioStream(inputStream);
            AudioPlayer.player.start(audios1);
        }
       catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_disarmButtonActionPerformed

    private void enableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableButtonActionPerformed
        // TODO add your handling code here:
        EnablePanel enablePanel = new EnablePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(enablePanel);                                       
    }//GEN-LAST:event_enableButtonActionPerformed

    private void disableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableButtonActionPerformed
        // TODO add your handling code here:
        DisablePanel disablePanel = new DisablePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(disablePanel);             
    }//GEN-LAST:event_disableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton armButton;
    private javax.swing.JButton disableButton;
    private javax.swing.JButton disarmButton;
    private javax.swing.JButton enableButton;
    private javax.swing.JButton removeButton;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
