package smart.home.security.view;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 * The notification banner view.
 * @author archana
 */
public class NotificationBanner extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form NotificationPanel
     */
    public NotificationBanner() {
        // Initialize the notification banner components.
        initComponents();
        // Add an mouse listener to self.
        addMouseListener(this);
    }

    /**
     * Helper to get the smart home security frame. 
     * @return the SmartHomeSecurityFrame of this component.
     */
    private SmartHomeSecurityFrame getSmartHomeSecurityFrame() {
        return SmartHomeSecurityFrame.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationLabel = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));

        notificationLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        notificationLabel.setForeground(new java.awt.Color(204, 0, 0));
        notificationLabel.setText("New Device Notification! Click to see details.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel notificationLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Invoked when the mouse button has been clicked (pressed
     * and released) on a component.
     */
    @Override
    public void mouseClicked(MouseEvent e) {
        // Create the notifications view.
        NotificationsPanel notificationsPanel = new NotificationsPanel();
        // Navigate from the current view to the notifications view.
        getSmartHomeSecurityFrame().replaceFramePanel(notificationsPanel);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        // Overridden - unused
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        // Overridden - unused
    }

    @Override
    public void mouseExited(MouseEvent e) {
        // Overridden - unused
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        // Overridden - unused
    }
}
